config/routes.rb
Rails.application.routes.draw do

	resources :products
	resources :auctions do
			resources :bids
	end
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :bids
end

app/models/bid.rb
class Bid < ActiveRecord::Base
    belongs_to :auction

    def amount_in_pounds
      if amount_in_pence.present?
        amount_in_pence / 100.00
      else
        0
      end
    end

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

	before_filter:find_auction, only: [:show,:destroy]


	def index
		@auctions = Auction.all
	end 

	def destroy
		@a.destroy
		redirect_to(auctions_url)
	end

	def new
		@auction = Auction.new
	end

	def create
		@auction = Auction.create(auction_params)
		redirect_to(@auction)
	end
	
	private

	def auction_params
		params.require(:auction).permit(:name,:description)
	end

	def find_auction
		id = params[:id]
		@a = Auction.find(id)
	end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

    before_filter(:find_auction, only: [:new,:create,:destroy])

  def new
    @bid=@auction.bids.build
  end

  def create
    @bid = @auction.bids.create(bid_params)
    redirect_to(@auction)
  end

  def destroy
    #@a.destroy
    #redirect_to(@auction)
  end

  private

  def bid_params
    params.require(:bid).permit(:amount_in_pence)
  end

  def find_auction
     @auction = Auction.find(params[:auction_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_filter:find_product, only: [:show,:destroy, :edit, :update]

	def index
		@products = Product.all
	end


	def new
		@page_title = "Create Product"
		@p = Product.new
	end

	def create
		
		@product = Product.create(product_params)
		flash[:notice] = "Created #{@product.title}"
		redirect_to(@product)
	end

	def destroy
		flash[:notice] = "#{@p.title} sucessfully deleted"
		@p.destroy
		redirect_to(products_url)
	end

	def edit
		@page_title = "Edit Product"
	end

	def update
		flash[:notice] = "Product updated"
		@p.update(product_params)
		redirect_to(@p)
	end


	private
	
	def product_params
		params.require(:product).permit(:title,:description)
	end

	def find_product
		id = params[:id]
		@p = Product.find(id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/auctions/index.erb
<p><strong>All Auctons are Funny</strong><br/><br/>

	<%@auctions.each do |a|%>
		<li><strong><%=link_to(a.name,auction_url(a))%></strong> ;<%=link_to("Delete",auction_url(a),method: :delete)%> </li>
<%end%>

<p>
	<%=link_to("New Auction",new_auction_url)%>
</p>
<p>
	<%=link_to("Have a look at Products",products_url)%>
</p>

app/views/auctions/new.erb
<%=form_for(@auction) do |f|%>
	<p><%=f.label(:name)%>
	<%=f.text_field(:name)%><br /><br />
	<%=f.label(:description)%>
	<%=f.text_area(:description)%></p>

<%=f.submit("Do it")%>
<%end%>

app/views/auctions/show.erb
<strong>Auction ID:<%=@a.id%> <br/><br/>
<%=@a.name%></strong><br/><br/>
<%=@a.description%>
<p>
  Bids<br/><br/>
  <%@a.bids.each do |b|%>
  <li>> <%=b.amount_in_pounds%></li>
  <%end%>

<p>
<%=link_to("Create New Bid",new_auction_bid_url(@a.id))%>
</p>
<p>
<%=link_to("Back to auctions",auctions_url)%>
</p>

app/views/bids/new.erb
<%=form_for([@auction,@bid]) do |f|%>
	<p><%=f.label(:amount_in_pence)%>
	<%=f.text_field(:amount_in_pence)%><br /><br />

<%=f.submit("Do it")%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<color="RED"><%if flash[:notice].present?%>
	<%=flash[:notice]%>
<br/><br>
<%end%> </color>
<%= yield %>

</body>
</html>

app/views/products/_form.erb
<%=@page_title%><br /><br />
<%=form_for(@p) do |f|%>
	<p><%=f.label(:title)%>
	<%=f.text_field(:title)%><br /><br />
	<%=f.label(:description)%>
	<%=f.text_area(:description)%></p>

<%=f.submit("Do it")%>
<%end%>

app/views/products/edit.erb
<%=render partial:"form"%>

app/views/products/index.erb
Hello World for the millionth time.

<strong>
	<%=Time.now%>
</strong>

<p>
	<%@products.each do |p| %>
		<li><strong><%=link_to(p.title,product_url(p))%></strong>  ; <%=time_ago_in_words(p.created_at)%> <%=link_to("Delete",product_url(p),method: :delete)%></li>
	<%end%>
</p>
<p>	
	<%=link_to("Worlds only search engine","http://www.Google.com")%>
</p>
<p>
	<%=link_to("New Product",new_product_url)%>
</p>
<p>
	<%=link_to("Have a look at Auctions",auctions_url)%>
</p>

app/views/products/new.erb
<%=render partial:"form"%>

app/views/products/show.erb
<strong>Product ID:<%=@p.id%> <br/><br/>
<%=@p.title%></strong><br/><br/>
<%=@p.description%>
<p>
<%=link_to("Edit Product",edit_product_url)%>
</p>
<p>
<%=link_to("Back to products",products_url)%>
</p>